export const allProjects: Project[] = [
  {
    title: "OC Trade",
    subtitle: null,
    startedAt: new Date(2024, 10),
    endedAt: null,
    descriptions: [
      "A copper price booking app for Oriental Copper, simplifying and automating the booking process for convenience.",
      "Developed entirely rewritten from iOS Swift to Flutter as the sole developer, utilizing Bloc/Cubit for state management, preserving all existing features while optimizing performance and maintaining the user experience. This includes implementing functionalities such as login, registration, price charts, booking, product catalog, notifications list, account management, change PIN, and change password, Firebase Analytics for user behavior tracking, Firebase Crashlytics for real-time error monitoring, Firebase Cloud Messaging for push notifications, SSL pinning to enhance security, and separate configurations for development and production environments",
    ],
    details: [],
    appIcon: "oc-trade-app-icon.png",
    images: ["oc-trade-01.png", "oc-trade-02.png", "oc-trade-03.png"],
    tabletImage: null,
    appleAppStoreUrl: "https://apps.apple.com/th/app/oc-trade/id1498887539",
    googlePlayStoreUrl:
      "https://play.google.com/store/apps/details?id=com.orientalcopper.app",
    gitHubUrl: null,
  },
  {
    title: "Easy Health",
    subtitle: null,
    startedAt: new Date(2024, 5),
    endedAt: new Date(2025, 0),
    descriptions: [
      "A food delivery app for Easy Health restaurant, specializing in healthy meals with a feature to track the nutritional intake of each dish and subscription for meal plan",
      "Developed entirely from scratch in Flutter as the sole developer, utilizing Bloc/Cubit for state management. Key features include login options (Apple, Facebook, Google, and email), email registration, a home page, branch list, product listing, cart management, checkout with Stripe SDK for payments, order summary, order status and history, multi-language support, push notifications, a profile page, an edit profile page, share images of meals to other apps, such as Instagram, integrate Google Maps for branches location and address, Firebase Analytics for user behavior tracking, Firebase Crashlytics for real-time error monitoring, Firebase Cloud Messaging for push notifications, SSL pinning to enhance security, and separate configurations for development, UAT, and production environments",
    ],
    details: [],
    appIcon: "easy-health-app-icon.png",
    images: ["easy-health-01.png", "easy-health-02.png", "easy-health-03.png"],
    tabletImage: null,
    appleAppStoreUrl: "https://apps.apple.com/th/app/easy-health/id6667109383",
    googlePlayStoreUrl:
      "https://play.google.com/store/apps/details?id=com.easyHealth.app",
    gitHubUrl: null,
  },
  {
    title: "Foamtec",
    subtitle: null,
    startedAt: new Date(2023, 10),
    endedAt: new Date(2025, 0),
    descriptions: [
      "A production line tracking app that allows staff to log their work progress at each station by scanning to start, pause, or complete tasks",
      "Developed entirely from scratch in Flutter as the sole developer, utilizing Bloc/Cubit for state management. Key features include task list, task detail, scan emplyee ID, scan work center and materials before start, submit quantity,and print label with Honeywell SDK for printing",
    ],
    details: [],
    appIcon: "foamtec-app-icon.png",
    images: [],
    tabletImage: "foamtec-01.png",
    appleAppStoreUrl: null,
    googlePlayStoreUrl: null,
    gitHubUrl: null,
  },
  {
    title: "Mewing by Mike Mew",
    subtitle: null,
    startedAt: new Date(2023, 7),
    endedAt: new Date(2025, 0),
    descriptions: [
      "Guided self-practice app for Mewing exercises with input from Dr. Mike Mew, the pioneer of Mewing techniques, The app offers subscription options on the Apple App Store and Google Play Store, transitioning from a paid model to a freemium model (free download with subscription plans)",
      "Developed entirely rewritten from Ionic to Flutter as the sole developer. Initially using GetX for state management, it was later migrated to Bloc/Cubit for better scalability and maintainability. Key features include login options (Apple, Facebook, Google, and email), email registration, a home page displaying practice programs, a selfie feature for tracking changes over time, a weekly well-being questionnaire, data visualization charts, blocking screen capture or recording in the video player, local notifications for reminders, multi-language support, A/B testing to optimize the user journey, Firebase Analytics for user behavior tracking, Firebase Crashlytics for real-time error monitoring, SSL pinning to enhance security, and separate configurations for development, and production environments",
    ],
    details: [],
    appIcon: "mewing-app-icon.png",
    images: ["mewing-01.png", "mewing-02.png", "mewing-03.png"],
    tabletImage: null,
    appleAppStoreUrl:
      "https://apps.apple.com/th/app/mewing-by-mike-mew/id1562833932",
    googlePlayStoreUrl:
      "https://play.google.com/store/apps/details?id=com.orthotropics.mewing",
    gitHubUrl: null,
  },
  {
    title: "El Mercado",
    subtitle: null,
    startedAt: new Date(2023, 5),
    endedAt: new Date(2025, 0),
    descriptions: [
      "A food delivery app for El Mercado restaurant",
      "Developed entirely from scratch in Flutter as the sole developer, utilizing GetX for state management. Key features include login options (Apple, Google, and email), email registration, a home page, product listing, cart management, checkout with Stripe SDK for payments, order summary, order status and history, multi-language support, push notifications, a profile page, an edit profile page, QR code scanning for dine-in ordering, integrate Google Maps for branches location and address, Firebase Analytics for user behavior tracking, Firebase Crashlytics for real-time error monitoring, Firebase Cloud Messaging for push notifications, Firebase Dynamic Links for marketing purposes, SSL pinning to enhance security, and separate configurations for development, UAT, and production environments",
    ],
    details: [],
    appIcon: "elmercado-app-icon.png",
    images: ["elmercado-01.png", "elmercado-02.png", "elmercado-03.png"],
    tabletImage: null,
    appleAppStoreUrl: "https://apps.apple.com/th/app/el-mercado/id6468034312",
    googlePlayStoreUrl:
      "https://play.google.com/store/apps/details?id=com.sybarite.elmercado",
    gitHubUrl: null,
  },
  {
    title: "El Mercado Staff",
    subtitle: null,
    startedAt: new Date(2023, 5),
    endedAt: new Date(2025, 0),
    descriptions: [
      "An internal app for El Mercado staff",
      "Developed entirely from scratch in Flutter as the sole developer, utilizing Bloc/Cubit for state management. Key features include login, product catalog, order management, table service management, incident reporting, multi-language support, push notifications, Firebase Analytics for user behavior tracking, Firebase Crashlytics for real-time error monitoring, Firebase Cloud Messaging for push notifications, SSL pinning to enhance security, and separate configurations for development, UAT, and production environments",
    ],
    details: [],
    appIcon: "elmercado-staff-app-icon.png",
    images: [
      "elmercado-staff-01.png",
      "elmercado-staff-02.png",
      "elmercado-staff-03.png",
    ],
    tabletImage: null,
    appleAppStoreUrl:
      "https://apps.apple.com/th/app/el-mercado-staff/id6472040124",
    googlePlayStoreUrl:
      "https://play.google.com/store/apps/details?id=com.sybarite.elmercado.staff",
    gitHubUrl: null,
  },
  {
    title: "JUST (v1.0.2 - 1.0.12)",
    subtitle: null,
    startedAt: new Date(2023, 2),
    endedAt: new Date(2023, 8),
    descriptions: [
      "A management tool for Volvo Thailand's central warehouse, featuring car inventory management, document scanning, inspections, and damage reporting",
      "Led development using Flutter, utilizing GetX for state management. Key features include login options (Apple, Facebook, Google, and email), email registration, car listing, submit car for sale, request loan process, Firebase Analytics for user behavior tracking, Firebase Crashlytics for real-time error monitoring, Firebase Cloud Messaging for push notifications, SSL pinning to enhance security, and separate configurations for development and production environments",
    ],
    details: [],
    appIcon: "just-app-icon.png",
    images: ["just-01.png", "just-02.png", "just-03.png"],
    tabletImage: null,
    appleAppStoreUrl: "https://apps.apple.com/th/app/just/id1633206350",
    googlePlayStoreUrl:
      "https://play.google.com/store/apps/details?id=com.justcar.justcar",
    gitHubUrl: null,
  },
  {
    title: "VCTPDS",
    subtitle: "Internal App for Volvo Cars Thailand Central Distribution",
    startedAt: new Date(2022, 10),
    endedAt: new Date(2025, 0),
    descriptions: [
      "A management tool for Volvo Thailand's central warehouse",
      "Developed entirely from scratch in Flutter as the sole developer, utilizing GetX for state management. Key features include login, car management, scan VIN numbers for quick identification, document scanning, SSL pinning to enhance security, and separate configurations for development, and production environments",
    ],
    details: [],
    appIcon: "vctpds-app-icon.png",
    images: ["vctpds-01.png", "vctpds-02.png", "vctpds-03.png"],
    tabletImage: null,
    appleAppStoreUrl: null,
    googlePlayStoreUrl: null,
    gitHubUrl: null,
  },
  {
    title: "Sabuy Wash (v1.0.0 - 1.0.5)",
    subtitle: null,
    startedAt: new Date(2022, 9),
    endedAt: new Date(2023, 7),
    descriptions: [
      "A location-based app to find and pay for nearby laundry machines at Sabuy Wash laundromats",
      "Developed entirely from scratch in Flutter as the sole developer, utilizing GetX for state management. Key features include login, email registration, integrate Google Maps for branch locations, order Status, branch information, machine selection and payment, Firebase Analytics for user behavior tracking, Firebase Crashlytics for real-time error monitoring, Firebase Cloud Messaging for push notifications, Firebase Dynamic Links for marketing purposes, SSL pinning to enhance security, and separate configurations for development, UAT, and production environments",
    ],
    details: [],
    appIcon: "sabuywash-app-icon.png",
    images: ["sabuywash-01.png", "sabuywash-02.png", "sabuywash-03.png"],
    tabletImage: null,
    appleAppStoreUrl: "https://apps.apple.com/th/app/sabuy-wash/id1659660313",
    googlePlayStoreUrl:
      "https://play.google.com/store/apps/details?id=com.sabuywash.sabuywashapp",
    gitHubUrl: null,
  },

  {
    title: "SBITO",
    subtitle: null,
    startedAt: new Date(2020, 10),
    endedAt: new Date(2025, 0),
    descriptions: [
      "A reward redemption and account management app for SBI Thai Online (SBITO) customers",
      "Responsibility for developed the account opening section using RxSwift. Key features include identity verification, selection of account types, and secure data submission. The flow supports multiple account types, including cash balance, credit balance, and mutual fund accounts, while also integrating with major banks for fast validation. This feature enhances the overall user experience by simplifying and speeding up the account creation process, Firebase Analytics for user behavior tracking, Firebase Crashlytics for real-time error monitoring, Firebase Cloud Messaging for push notifications, and separate configurations for development, UAT, and production environments",
    ],
    details: [],
    appIcon: "sbito-app-icon.png",
    images: ["sbito-01.png", "sbito-02.png", "sbito-03.png"],
    tabletImage: null,
    appleAppStoreUrl: "https://apps.apple.com/th/app/sbito/id1533272611",
    googlePlayStoreUrl: null,
    gitHubUrl: null,
  },
  {
    title: "evRiderz",
    subtitle: null,
    startedAt: new Date(2021, 7),
    endedAt: new Date(2023, 2),
    descriptions: [
      "A dual-purpose app for food delivery and transportation services",
      "iOS app (native) with RxSwift, Developed entirely from scratch as the sole developer. Key features include login options (Apple, Facebook, Google, and email), email registration, a home page, restaurant list, product listing, cart management, checkout with 2C2P SDK for payments, order status and history, multi-language support, push notifications, a profile page, an edit profile page, integrate Google Maps for branches location and address, Firebase Analytics for user behavior tracking, Firebase Crashlytics for real-time error monitoring, Firebase Cloud Messaging for push notifications, Firebase Dynamic Links for marketing purposes, and separate configurations for development, UAT, and production environments",
    ],
    details: [],
    appIcon: "evriderz-app-icon.png",
    images: ["evriderz-01.png", "evriderz-02.png", "evriderz-03.png"],
    tabletImage: null,
    appleAppStoreUrl: null,
    googlePlayStoreUrl: null,
    gitHubUrl: null,
  },
  {
    title: "evDriverz",
    subtitle: null,
    startedAt: new Date(2021, 7),
    endedAt: new Date(2023, 2),
    descriptions: [
      "An app for Driver to recieve ride jobs from evRiderz",
      "iOS app (native) with RxSwift, Led development entirely from scratch. Key features include login, registration, a home page, implementing Socket.IO for real-time status updates. This integration ensured that drivers were promptly notified of new orders, order detail, incomes status, multi-language support, push notifications, a profile page, an edit profile page, integrate Google Maps for restaurant and destination location and address, Firebase Analytics for user behavior tracking, Firebase Crashlytics for real-time error monitoring, Firebase Cloud Messaging for push notifications, and separate configurations for development, UAT, and production environments",
    ],
    details: [],
    appIcon: "evdriverz-app-icon.png",
    images: ["evdriverz-01.png", "evdriverz-02.png", "evdriverz-03.png"],
    tabletImage: null,
    appleAppStoreUrl: null,
    googlePlayStoreUrl: null,
    gitHubUrl: null,
  },
  {
    title: "Rabbit Rewards (v2.0.0 - 2.1.6)",
    subtitle: null,
    startedAt: new Date(2019, 10),
    endedAt: new Date(2023, 2),
    descriptions: [
      "A loyalty app for redeeming rewards and subscription for trips",
      "iOS app (native) with RxSwift, Led the development of the entire app. Key features include login, registration, point redemption, subscription management, user challenges, card management, Firebase Analytics for user behavior tracking, Firebase Crashlytics for real-time error monitoring, Firebase Cloud Messaging for push notifications, Firebase Dynamic Links for marketing purposes, and separate configurations for development, UAT, and production environments",
    ],
    details: [],
    appIcon: "rabbitrewards-app-icon.png",
    images: [
      "rabbitrewards-01.png",
      "rabbitrewards-02.png",
      "rabbitrewards-03.png",
    ],
    tabletImage: null,
    appleAppStoreUrl: null,
    googlePlayStoreUrl: null,
    gitHubUrl: null,
  },
  {
    title: "SCG Family",
    subtitle: null,
    startedAt: new Date(2021, 0),
    endedAt: new Date(2021, 4),
    descriptions: [
      "Implements cash card registration and access to related SCG Family benefits and information",
      "iOS app (native), I was responsible for the membership component before the app was discontinued. My contributions included creating both UAT and production environments, as well as implementing cash card registration and related information features.",
    ],
    details: [],
    appIcon: "scgfamily2020-app-icon.png",
    images: [
      "scgfamily2020-01.png",
      "scgfamily2020-02.png",
      "scgfamily2020-03.png",
    ],
    tabletImage: null,
    appleAppStoreUrl: null,
    googlePlayStoreUrl: null,
    gitHubUrl: null,
  },
  {
    title: "PERFUMIST Perfumes Advisor",
    subtitle: null,
    startedAt: new Date(2019, 9),
    endedAt: new Date(2021, 11),
    descriptions: [
      "A personalized perfume advisor app with features for exploring fragrance notes and getting recommendations tailored to user preferences",
      "iOS app (native) with RxSwift, Led the development of the entire app, converting all pages to use RxSwift for more efficient and responsive code. After the refactoring process, I continued to implement all new features, ensuring optimal performance and a seamless user experience.",
    ],
    details: [],
    appIcon: "perfumist-app-icon.png",
    images: ["perfumist-01.png", "perfumist-02.png", "perfumist-03.png"],
    tabletImage: null,
    appleAppStoreUrl: null,
    googlePlayStoreUrl: null,
    gitHubUrl: null,
  },
  {
    title: "Dota Heroes",
    subtitle: null,
    startedAt: null,
    endedAt: null,
    descriptions: [
      "Flutter project to teach internship student using Bloc/Cubit",
    ],
    details: [
      {
        title: "API",
        bullets: ["https://docs.opendota.com/"],
      },
    ],
    appIcon: null,
    images: ["dotaheroes-01.png", "dotaheroes-02.png", "dotaheroes-03.png"],
    tabletImage: null,
    appleAppStoreUrl: null,
    googlePlayStoreUrl: null,
    gitHubUrl: "https://github.com/knottx/dota-heroes-flutter",
  },
  {
    title: "Weather",
    subtitle: null,
    startedAt: null,
    endedAt: null,
    descriptions: ["Flutter project to teach internship student using GetX"],
    details: [
      {
        title: "API",
        bullets: ["https://openweathermap.org/api"],
      },
    ],
    appIcon: null,
    images: ["weather-01.png", "weather-02.png", "weather-03.png"],
    tabletImage: null,
    appleAppStoreUrl: null,
    googlePlayStoreUrl: null,
    gitHubUrl: null,
  },
];
